spring:
  rabbitmq:
    addresses: 172.16.12.250
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: auto
        max-concurrency: 30
        prefetch: 1
        
  http:
    encoding:
      charset: utf-8
      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    
server:
  port: 8081
  servlet:
    context-path: /
    
logging:
  config: classpath:logback-spring.xml
  file: log/consumer.log
  level:
    root: info